language: go

go:
- 1.11.1

notifications:
  email:
    recipients:
      - lamuguo@gmail.com
  on_success: change
  on_failure: always

sudo: false

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - which dep

install:
  - dep ensure
  - go build -o /tmp/server .

addons:
  ssh_known_hosts: tech-meetup.com

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f19aef1f28f7_key -iv $encrypted_f19aef1f28f7_iv -in deploy/id_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh -p22 root@tech-meetup.com '/bin/bash -s' < deploy/deploy.sh

