version: "3.9"

services:
  meetup:
    build:
      context: .
      dockerfile: Dockerfile
    image: lamuguo/meetup:live
    command: ["/go/bin/blog", "-http=0.0.0.0:80", "-vhost_map=blog.tech-meetup.com=testing/|lamuguo.tech-meetup.com=lamuguo/"]
    ports:
      - "8899:8080"
    restart: always
